Create top navbar and partials
dani-wilson/little-shop-7 pull request #71
Opened 2023-07-27 19:42 UTC by MWoodshop

# Describe the changes below:
Uses @westonio menu design from the _admin menu partial
Creates a new partial for visitor menu
Adds admin partial to all admin views
Adds visitor partial to all visitor (non-admin) views
Adds unique menu to root page to select Admin or Visitor to avoid a 404 when accessing the main website*
Adds link to page header text to return to root page
Adds merchant controller and index view page for a user to select their merchant as opposed to having to type it in.*

*Note: I don't see any future user stories addressing this but if there is we can just undo these changes.

# Relevant user story: N/A

# Specific feedback requests? Include file name and line:

# Before submitting, check the following:
- [X] Entire test suite is passing
- [X] SimpleCov test percentage (100%)

# Note any co-authors / anything else you'd like to add:
Discussed in morning standup. Please let me know if anything looks off and I can change/undo anything.

2023-07-27 21:02 UTC, westonio requested changes

2023-07-27 21:02 UTC, westonio commented on app/views/shared/_admin_topper.html.erb
> +</div>
Not sure if it was intended, but these seem unused and possible made it in there as a mistake @MWoodshop

2023-07-27 21:02 UTC, westonio commented on app/views/shared/_visitor_topper.html.erb
> +</div>
Same thing here - is there a reason there are `<div>`s without content in them?

2023-07-27 21:07 UTC, MWoodshop commented on app/views/shared/_admin_topper.html.erb
> +</div>
Lines 1-5 are adding a clickable link to the main header "Little Esty Shop" to get back to the root page. We can remove before final submission if we don't want it but at least for debugging purposes it lets get to the main page from anywhere.

Lines 25-28 follows the wireframe of having a horizonal bar under the header and nav bar and before the content of eachpage.

2023-07-27 21:10 UTC, MWoodshop commented on app/views/shared/_admin_topper.html.erb
> +</div>
Actually the <div class="container"></div> is no longer being used. I'll remove that. The separator is still being used however.

2023-07-27 22:33 UTC, westonio commented on app/views/shared/_admin_topper.html.erb
> +</div>
Oh gotcha - I just wanted to make sure it wasn't an accident or erroneous.  If it's intended -- no worries, I will approve.

2023-07-27 22:33 UTC, westonio approved these changes

2023-07-28 02:35 UTC, dani-wilson approved these changes
Looks nice!

2023-07-28 14:54 UTC, merged